baseURL: "https://repeatr.io/"
title: "Timeless Stack"

contentDir:    "content"
themesDir:     "themes"
layoutDir:     "hugo/layouts" # aka templates (but these are mostly in themes anyway)
archetypeDir:  "hugo/archetypes" # aka "content templates" aka "i will never use these"
staticDir:     "hugo/static" # avoids processing, but do not understand why distinct from assertDir
dataDir:       "hugo/data" # avoids processing, but do not understand why distinct from assertDir
assetDir:      "hugo/assets" # avoids processing, but do not understand why there's three of these
publishDir:    "hugo/_publish"
resourceDir:   "hugo/_resources" # appears to be used by hugo when generating things?

#disableLiveReload: true
#disableHugoGeneratorInject: true
disableKinds: ["taxonomy", "taxonomyTerm"]

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 4

theme: "book"

params:
  BookSection: "*"
